//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Nzg.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW_NZG                101
#define IDD_FORMVIEW_2DPLOT             102
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_NzgTYPE                     130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_POPUP                       310
#define IDR_PLOT2D_TYPE                 315
#define IDC_BUTTON_PLAY                 1001
#define IDC_BUTTON_PLAY2                1002
#define IDC_EDIT_VALUE_STEP             1003
#define IDC_EDIT_ISO_STEP               1004
#define IDC_COMBO_VIEW_AT               1005
#define IDC_EDIT_COLOR_STEP             1006
#define IDC_COMBO_LABELS                1007
#define IDC_BUTTON_RESET                1008
#define IDC_EDIT_ROWS                   1009
#define IDC_CHECK_POLAR                 1010
#define IDC_CUSTOM_PLOT                 1011
#define IDC_CHECK_0GRID                 1012
#define IDC_CHECK_RAINBOW               1013
#define IDC_CHECK_MASK                  1014
#define IDC_EDIT_ISO_STEP2              1015
#define IDC_EDIT_COLS                   1015
#define IDC_BUTTON_SAVE                 1071
#define IDC_BUTTON_LOAD                 1072
#define IDC_CHECK_X_AUTO                1136
#define IDC_CHECK_Y_AUTO                1140
#define IDC_EDIT_Y_MIN                  1141
#define IDC_EDIT_Y_MAX                  1142
#define IDC_EDIT_X_MAX                  1144
#define IDC_EDIT_X_MIN                  1145
#define IDC_EDIT_Y_DIVS                 1253
#define IDC_EDIT_X_DIVS                 1254
#define IDC_BUTTON_ADD_COMMENT          1256
#define IDC_BUTTON_REMOVE_COMMENTS      1257
#define ID_NEW_NON                      32771
#define ID_NONE_REMOVEALL               32772
#define ID_NZG_VIEW                     32773
#define ID_NEW_PLOT2D                   32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           316
#endif
#endif
